language: r
os: linux
cache: packages

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true

notifications:
  email:
    on_success: change
    on_failure: change
